// One-time (re)generation of packages/js/src/button-core/brand.ts.
// The wordmark is Space Grotesk 600 outlined to a path so no web font is ever loaded.
// FIANTO_BRAND_FONT overrides the default font path (the merchant-frontend checkout of the font).
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import * as fontkit from 'fontkit';

const FONT = resolve(process.env.FIANTO_BRAND_FONT ?? '../merchant-frontend/src/app/fonts/space-grotesk-600.woff2');
const font = fontkit.openSync(FONT);
const run = font.layout('fianto');
let x = 0;
const parts = [];
for (let i = 0; i < run.glyphs.length; i++) {
  const glyph = run.glyphs[i];
  const path = glyph.path.scale(1, -1).translate(x + run.positions[i].xOffset, 0);
  parts.push(path.toSVG());
  x += run.positions[i].xAdvance;
}
const ascent = font.ascent;
const descent = -font.descent;
const MARK = [
  'M 620,377 L 790,377 A 68 68 0 0 1 858,445 L 858,524 A 14 14 0 0 1 844,538 L 766,538 C 748,536 736,522 736,504 L 736,496 L 484,496 Q 472,496 481,488 L 603,385 Q 612,377 620,377 Z',
  'rotate180',
  'M 624,562 L 835,562 A 66 66 0 0 1 835,694 L 672,694 A 48 48 0 0 1 624,646 L 624,562 Z',
  'M 391,515 L 554,515 A 48 48 0 0 1 602,563 L 602,647 L 391,647 A 66 66 0 0 1 391,515 Z',
];
const out = `// Generated by scripts/build-brand.mjs. Do not edit.
// Mark: merchant-frontend/src/components/ui/logo.tsx. Wordmark: Space Grotesk 600 (OFL) outlined.

export const MARK_VIEWBOX = '240 240 774 774';
export const MARK_TRANSFORM = 'translate(627 627) scale(1.3) translate(-613 -604.5)';
/** The second path is the first rotated 180° about (613, 604.5). */
export const MARK_PATHS = ${JSON.stringify([MARK[0], MARK[0], MARK[2], MARK[3]])} as const;
export const MARK_ROTATED_INDEX = 1;
export const WORDMARK_VIEWBOX = '0 ${-ascent} ${Math.ceil(x)} ${ascent + descent}';
export const WORDMARK_PATH = ${JSON.stringify(parts.join(' '))};
`;
writeFileSync('packages/js/src/button-core/brand.ts', out);
console.log('packages/js/src/button-core/brand.ts written');
